apiVersion: v1
kind: Service
metadata:
  name: awesomebuilder-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  type: LoadBalancer
  selector:
    app: awesomebuilder-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awesomebuilder-app
  annotations:
    kubernetes.io/change-cause: updateapptitle
spec:
  replicas: 2
  selector:
    matchLabels:
      app: awesomebuilder-ui
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2        # how many pods we can add at a time
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: awesomebuilder-ui
    spec:
      containers:
        - name: awesomebuilder
          image: public.ecr.aws/m8o2b2o2/awesomebuilder:242c3aec107eb50925565d990c41769307114e1b
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 100m
